name: supa_addons
description: "A Flutter package that extends Supabase with crash reporting, push notifications, and remote config — production-ready and wired to your Supabase project out of the box."
version: 0.0.1
homepage:  https://github.com/Abdelrahmanyehia9/supa_addons.git

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  supa_helper: ^0.1.4
  onesignal_flutter: ^5.5.4
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0